name: GVSOC MR CI
on: pull_request
jobs:
  Regression-Tests:
    name: Regression Tests
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
      - name: Build GVSOC
        run: |
          cd ${{ github.workspace }}
          sudo apt-get update -y
          sudo apt-get install -y build-essential git doxygen python3-pip libsdl2-dev curl cmake gtkwave libsndfile1-dev rsync autoconf automake texinfo libtool pkg-config libsdl2-ttf-dev
          pip3 install -r core/requirements.txt
          pip3 install -r gapy/requirements.txt
          make all TARGETS=pulp-open
          export -p > temp_env
      - name: Launch GVSOC Regression Tests
        run: |
          cd ${{ github.workspace }}
          source temp_env
          ./install/bin/gvsoc --target=pulp-open --binary examples/pulp-open/hello image flash run > regression_report.txt
          export -p > temp_env
      - name: Read GVSOC Regression Report
        run: |
          cd ${{ github.workspace }}
          source temp_env
          echo "Reading regression report from $(pwd) folder"
          cat regression_report.txt
          cd ${{ github.workspace }}
          export -p > temp_env
      - name: Upload GVSOC Regression Report
        uses: actions/upload-artifact@v3
        with:
          name: regression_report
          path: regression_report.txt
      - name: Upload GVSOC BUILD folder
        uses: actions/upload-artifact@v3
        with:
          name: BUILD_GVSOC
          path: BUILD
      - name: Exit from GVSOC CI
        run: |
          echo "This job's status is ${{ job.status }}."
          if grep -q "unexpected fail" ${{ github.workspace }}/regression_report.txt; then exit 1; fi
